import { AsyncLocalStorage } from 'async_hooks';

export interface TenantState {
  companyId?: string;
  requestId?: string;
}

/**
 * AsyncLocalStorage-based tenant + request context.
 *
 * Every incoming HTTP request gets its own execution context with:
 * - requestId: UUID generated by RequestIdInterceptor (every request)
 * - companyId: set by JwtGuard after token verification (authenticated requests)
 *
 * All downstream services, Prisma queries, audit logs, and error responses
 * can read from this store without explicit parameter passing.
 */
export const TenantContext = new AsyncLocalStorage<TenantState>();
